/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

// const { sidebar: apiSidebar } = require("./sidebars/api");

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // apiSidebar,

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "category",
      label: "PCF系列基础工具指引",
      link: { type: "doc", id: "PCF系列基础工具指引" },
      items: [
        "pcf-tools/关于AICP产品碳足迹系列工具",
        "pcf-tools/汽车生命周期评价工具",
        "pcf-tools/汽车产品系统管理工具",
        "pcf-tools/汽车产品碳足迹实景计算工具",
        "pcf-tools/验证管理模块",
      ],
    },
    {
      type: "category",
      label: "开放平台",
      items: [
        "api/introduction",
        {
          type: "category",
          label: "API 列表",
          collapsed: false,
          items: ["api/newToken", "api/uploadModel", "api/uploadModelParams"],
        },
      ],
    },
  ],
};

module.exports = sidebars;
