/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

const { sidebar: apiSidebar } = require("./sidebars/api");

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  apiSidebar,

  // But you can create a sidebar manually

  tutorialSidebar: [
    {
      type: "doc",
      label: "关于GTech",
      id: "introduction",
    },
    {
      type: "doc",
      label: "关于AICP产品碳足迹系列工具",
      id: "about-aicp-tools",
    },
  ],
};

module.exports = sidebars;
